# Generated by Django 4.2.3 on 2023-12-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Amount')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Amount')),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
        ),
    ]
