# Generated by Django 4.2.3 on 2023-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opendate', models.DateTimeField(auto_now_add=True, verbose_name='Open Date')),
                ('issuename', models.CharField(max_length=100, verbose_name='Issue Name')),
                ('issuedesc', models.TextField(verbose_name='Isssue Description')),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=20, verbose_name='Priority Level')),
                ('issueopen', models.BooleanField(default=True, verbose_name='Issue Open')),
                ('closedate', models.DateTimeField(blank=True, null=True, verbose_name='Closed Date')),
            ],
        ),
    ]
