from django import forms

class Budget(forms.Form):
	a_gross_pay = forms.DecimalField(label="Annual Gross Salary", decimal_places=2)
	a_gross_bonus = forms.DecimalField(label="Annual Gross Bonus", decimal_places=2)
	a_al_taxable = forms.DecimalField(label="Alyssa Taxable Salary", decimal_places=2)
	a_al_fwh = forms.DecimalField(label="Alyssa Federal Withholding", decimal_places=2)
	a_al_swh = forms.DecimalField(label="Alyssa State Withholding", decimal_places=2)
	bw_medical = forms.DecimalField(label="Medical", decimal_places=2)
	bw_dental = forms.DecimalField(label="Dental", decimal_places=2)
	bw_daycare  = forms.DecimalField(label="Daycare", decimal_places=2)
	rate_sstax  = forms.DecimalField(label="Social Security Tax Rate", decimal_places=2) 
	rate_medicare  = forms.DecimalField(label="Medicare Tax Rate", decimal_places=2)
	rate_401k  = forms.DecimalField(label="401k Contribution Pct", decimal_places=2)
	w_train = forms.DecimalField(label="NJ Transit (Weekly)", decimal_places=2)
	rate_r401k = forms.DecimalField(label="Roth 401k Contribution Pct", decimal_places=2)
	bw_arag = forms.DecimalField(label="Legal", decimal_places=2)
	a_daycare_payback = forms.DecimalField(label="Daycare Payback", decimal_places=2)
	w_school = forms.DecimalField(label="School", decimal_places=2)
	m_internet = forms.DecimalField(label="Internet", decimal_places=2)
	m_phone = forms.DecimalField(label="Phone", decimal_places=2)
	m_electric = forms.DecimalField(label="Electric", decimal_places=2)
	m_natgas = forms.DecimalField(label="Gas", decimal_places=2)
	a_carins = forms.DecimalField(label="Car Insurance (Annual)", decimal_places=2)
	m_homeins = forms.DecimalField(label="Homeowners Insurance (Monthly)", decimal_places=2)
	m_apple = forms.DecimalField(label="Apple", decimal_places=2)
	m_cabin_mtg = forms.DecimalField(label="Cabin Mortgage", decimal_places=2)
	a_cabin_ptax = forms.DecimalField(label="Cabin Property Tax", decimal_places=2)
	a_cabin_ins = forms.DecimalField(label="Cabin Homeowners Insurance", decimal_places=2)
	m_cabin_electric = forms.DecimalField(label="Cabin Electric", decimal_places=2)
	m_cabin_cable = forms.DecimalField(label="Cabin Cable", decimal_places=2)
	a_cabin_hoa = forms.DecimalField(label="Cabin HOA (Annual)", decimal_places=2)
	m_car = forms.DecimalField(label="Car Payment", decimal_places=2)
	m_mtg = forms.DecimalField(label="Home Mortgage", decimal_places=2)
	a_ptax = forms.DecimalField(label="Home Property Tax", decimal_places=2)