# Generated by Django 4.2.10 on 2024-02-23 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0038_payee_def_gcat"),
        ("csv_importer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staged_transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fin.account",
            ),
        ),
    ]
