# Generated by Django 5.0.2 on 2024-03-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fin", "0040_groupedcat_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.CharField(blank=True, max_length=255, null=True)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fin.account"
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fin.payee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlowItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fixed.flow"
                    ),
                ),
                (
                    "groupedcat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fin.groupedcat"
                    ),
                ),
            ],
        ),
    ]
