# Generated by Django 4.2.3 on 2023-12-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fin', '0033_delete_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100, verbose_name='Budget Item')),
                ('itemFreq', models.CharField(choices=[('Once', 'Once'), ('Annual', 'Annual'), ('Semiannual', 'Semiannual'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly'), ('Biweekly', 'Biweekly'), ('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Weekends', 'Weekends'), ('Officedays', 'Officedays'), ('Homeworkdays', 'Homeworkdays'), ('Vacationdays', 'Vacationdays')], default='Monthly', max_length=20, verbose_name='Frequency')),
                ('itemAmt', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Amount')),
                ('itemCat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fin.category')),
            ],
        ),
    ]
