# Generated by Django 4.2.3 on 2023-12-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tid',
            field=models.IntegerField(null=True),
        ),
    ]
