# Generated by Django 4.2.3 on 2023-12-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_tid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtransaction',
            options={'ordering': ['-amount']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['tdate', '-amount']},
        ),
    ]
