# Generated by Django 5.0.2 on 2024-02-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_remove_subtransaction_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Csv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.FileField(upload_to="csvs")),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("activated", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["tdate"]},
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="amount",
        ),
    ]
