# Generated by Django 5.0.2 on 2024-02-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_csv_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Csv",
        ),
    ]
