# Generated by Django 5.0.2 on 2024-02-27 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0040_groupedcat_active"),
        ("transactions", "0007_paycheck_paycheckitems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paycheck",
            old_name="desc",
            new_name="note",
        ),
        migrations.AddField(
            model_name="paycheck",
            name="payee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fin.payee",
            ),
        ),
        migrations.AddField(
            model_name="paycheck",
            name="tdate",
            field=models.DateField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AddField(
            model_name="paycheckitems",
            name="paycheck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="transactions.paycheck",
            ),
        ),
    ]
