# Generated by Django 5.0.2 on 2024-02-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_rename_desc_paycheck_note_paycheck_payee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paycheck",
            name="tdate",
        ),
    ]
