# Generated by Django 5.0.2 on 2024-02-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_remove_paycheck_tdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paycheckitems",
            name="active",
        ),
        migrations.RemoveField(
            model_name="paycheckitems",
            name="added",
        ),
    ]
