# Generated by Django 5.0.2 on 2024-03-08 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fin", "0040_groupedcat_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax_Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fin.payee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tax_Return_Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("desc", models.CharField(blank=True, max_length=255, null=True)),
                ("outbound", models.BooleanField(blank=True, default=True, null=True)),
                (
                    "tax_return",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tax.tax_return",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tax_Return_Form_Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=255, null=True)),
                ("line", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "instructions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tax_return_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tax.tax_return_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Return_Form_Line_Input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        null=True,
                        verbose_name="Amount",
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tax_return_form_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tax.tax_return_form_line",
                    ),
                ),
            ],
        ),
    ]
