# Generated by Django 5.0.2 on 2024-03-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Return_Form_Line_Input",
            new_name="Tax_Return_Form_Line_Input",
        ),
        migrations.RemoveField(
            model_name="tax_return",
            name="payee",
        ),
    ]
