# Generated by Django 5.0.2 on 2024-03-09 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0040_groupedcat_active"),
        (
            "tax",
            "0002_rename_return_form_line_input_tax_return_form_line_input_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tax_return",
            name="payee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fin.payee",
            ),
        ),
    ]
