# Generated by Django 5.0.2 on 2024-03-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0003_tax_return_payee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tax_return_form",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="tax_return_form",
            name="outbound",
        ),
        migrations.AddField(
            model_name="tax_return_form_line_input",
            name="desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
