# Generated by Django 5.0.2 on 2024-03-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0005_datasource_inputvalue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputvalue",
            name="multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=1.0,
                max_digits=18,
                null=True,
                verbose_name="Amount",
            ),
        ),
    ]
