# Generated by Django 5.0.2 on 2024-03-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0006_inputvalue_multiplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputvalue",
            name="multiplier",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=1.0, max_digits=18, null=True
            ),
        ),
    ]
