# Generated by Django 5.0.2 on 2024-03-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0008_remove_inputvalue_multiplier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tax_return_form_line_input",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="tax_return_form_line_input",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="tax_return_form_line_input",
            name="text",
        ),
    ]
