# Generated by Django 4.2.3 on 2023-07-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0002_alter_account_account_alter_category_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
