# Generated by Django 4.2.3 on 2023-07-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0004_alter_transaction_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
