# Generated by Django 4.2.3 on 2023-08-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0005_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opendate', models.DateTimeField(auto_now_add=True)),
                ('issuename', models.CharField(max_length=100)),
                ('issuedesc', models.TextField()),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='payee',
            options={'ordering': ['payee']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['tdate', 'amount']},
        ),
    ]
