# Generated by Django 4.2.3 on 2023-08-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0006_issue_alter_account_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='closedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issueopen',
            field=models.BooleanField(default=True),
        ),
    ]
