# Generated by Django 4.2.3 on 2023-08-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0007_issue_closedate_issue_issueopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='payee',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='closedate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed Date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuedesc',
            field=models.TextField(verbose_name='Isssue Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuename',
            field=models.CharField(max_length=100, verbose_name='Issue Name'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issueopen',
            field=models.BooleanField(default=True, verbose_name='Issue Open'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='opendate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Open Date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=20, verbose_name='Priority Level'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.category', to_field='category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.payee', to_field='payee', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tdate',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
