# Generated by Django 4.2.3 on 2023-08-10 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0009_alter_transaction_account_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(null=True)),
                ('tdate', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Amount')),
                ('match', models.CharField(blank=True, max_length=255, null=True)),
                ('oldCat', models.CharField(blank=True, max_length=255, null=True)),
                ('oldPayee', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.category')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.payee')),
            ],
            options={
                'ordering': ['tdate', 'amount'],
            },
        ),
    ]
