# Generated by Django 4.2.3 on 2023-08-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0011_trans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tran',
            name='account',
        ),
        migrations.RemoveField(
            model_name='tran',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tran',
            name='payee',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Tran',
        ),
    ]
