# Generated by Django 4.2.3 on 2023-08-10 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fin', '0012_remove_tran_account_remove_tran_category_and_more'),
    ]

    operations = [
    ]