# Generated by Django 4.2.3 on 2023-10-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0014_budgetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='itemAmt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='itemFreq',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly')], default='Monthly', max_length=20, verbose_name='Frequency'),
        ),
    ]
