# Generated by Django 4.2.3 on 2023-10-20 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0016_budgetitem_itemnote_alter_budgetitem_itemfreq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='itemNote',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='itemCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fin.category'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='itemFreq',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Semiannual', 'Semiannual'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly'), ('Biweekly', 'Biweekly'), ('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Weekends', 'Weekends'), ('Officedays', 'Officedays'), ('Homeworkdays', 'Homeworkdays')], default='Monthly', max_length=20, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='itemName',
            field=models.CharField(max_length=100, verbose_name='Budget Item'),
        ),
    ]
