# Generated by Django 4.2.3 on 2023-10-20 18:22

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0017_remove_budgetitem_itemnote_budgetitem_itemcat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayee',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payee',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
