# Generated by Django 4.2.3 on 2023-10-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0018_historicalpayee_tags_payee_tags'),
    ]

    operations = [
    ]

'''
from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0018_historicalpayee_tags_payee_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrans',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trans',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
'''