# Generated by Django 4.2.3 on 2023-10-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0020_category_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='itemFreq',
            field=models.CharField(choices=[('Once', 'Once'), ('Annual', 'Annual'), ('Semiannual', 'Semiannual'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly'), ('Biweekly', 'Biweekly'), ('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Weekends', 'Weekends'), ('Officedays', 'Officedays'), ('Homeworkdays', 'Homeworkdays'), ('Vacationdays', 'Vacationdays')], default='Monthly', max_length=20, verbose_name='Frequency'),
        ),
    ]
