# Generated by Django 4.2.3 on 2023-11-02 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0023_rename_jobs_job_category_l1group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupedCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fin.category')),
                ('l1group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fin.l1group')),
            ],
        ),
    ]
