# Generated by Django 4.2.3 on 2023-11-02 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0024_groupedcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='l1group',
        ),
        migrations.AddField(
            model_name='historicaltrans',
            name='groupedcat',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fin.groupedcat'),
        ),
        migrations.AddField(
            model_name='trans',
            name='groupedcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fin.groupedcat'),
        ),
    ]
