# Generated by Django 4.2.3 on 2023-11-14 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0025_remove_category_l1group_historicaltrans_groupedcat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupedcat',
            options={'ordering': ['l1group__l1group', 'category']},
        ),
        migrations.AlterModelOptions(
            name='l1group',
            options={'ordering': ['l1group']},
        ),
        migrations.AlterModelOptions(
            name='trans',
            options={'ordering': ['category']},
        ),
        migrations.AddField(
            model_name='l1group',
            name='aligned_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fin.category'),
        ),
    ]
