# Generated by Django 4.2.3 on 2023-11-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0026_alter_groupedcat_options_alter_l1group_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
