# Generated by Django 4.2.3 on 2023-11-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0028_issue_historicalpayee_slug_payee_slug'),
    ]

    operations = [
        #migrations.AlterField(
        #    model_name='payee',
        #    name='slug',
        #    field=models.SlugField(blank=True, null=True, unique=True),
        #),
    ]
