# Generated by Django 4.2.3 on 2023-12-01 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0030_alter_budgetitem_itemcat_alter_groupedcat_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
