# Generated by Django 4.2.3 on 2023-12-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0031_delete_job_delete_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trans',
            options={'ordering': ['tdate', '-amount']},
        ),
    ]
