# Generated by Django 4.2.3 on 2023-12-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0032_alter_trans_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
