# Generated by Django 4.2.3 on 2023-12-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0033_delete_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetItem',
        ),
    ]
