# Generated by Django 4.2.3 on 2023-12-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0034_delete_budgetitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trans',
            name='account',
        ),
        migrations.RemoveField(
            model_name='trans',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trans',
            name='groupedcat',
        ),
        migrations.RemoveField(
            model_name='trans',
            name='payee',
        ),
        migrations.DeleteModel(
            name='HistoricalTrans',
        ),
        migrations.DeleteModel(
            name='Trans',
        ),
    ]
