# Generated by Django 4.2.3 on 2023-12-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0035_remove_trans_account_remove_trans_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l1group',
            name='aligned_category',
        ),
    ]
