# Generated by Django 5.0.2 on 2024-02-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0036_remove_l1group_aligned_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={},
        ),
    ]
