# Generated by Django 5.0.2 on 2024-02-17 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0037_alter_account_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payee",
            name="def_gcat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fin.groupedcat",
            ),
        ),
    ]
