# Generated by Django 5.0.2 on 2024-02-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0038_payee_def_gcat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["account"]},
        ),
    ]
