# Generated by Django 5.0.2 on 2024-02-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0039_alter_account_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupedcat",
            name="active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
