# Generated by Django 4.2.3 on 2023-07-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_phone_alter_member_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
